import { Router } from "express";
import { CreateTurmaController } from "./controllers/CreateTurmaController";
import { CreateCatequeseAdultosController } from "./controllers/CreateCatequeseAdultosController";
import { CreatePessoaController } from "./controllers/CreatePessoaController";
import { CreateSacramentoController } from "./controllers/CreateSacramentoController";
import { CreatePadrinhoMadrinhaController } from "./controllers/CreatePadrinhoMadrinhaController";
import { CreateBatismoController } from "./controllers/CreateBatismoController";
import { CreateAdmissaoController } from "./controllers/CreateAdmissaoController";
import { CreateEucaristiaPrimeiraController } from "./controllers/CreateEucaristiaPrimeiraController";
import { CreateCrismaController } from "./controllers/CreateCrismaController";
import { FindTurmaController } from "./controllers/FindTurmaController";
import { FindCatequeseAdultosController } from "./controllers/FindCatequeseAdultosController";
import { FindPessoaController } from "./controllers/FindPessoaController";
import { FindSacramentoController } from "./controllers/FindSacramentoController";
import { FindPadrinhoMadrinhaController } from "./controllers/FindPadrinhoMadrinhaController";
import { FindBatismoController } from "./controllers/FindBatismoController";
import { FindAdmissaoController } from "./controllers/FindAdmissaoController";
import { FindEucaristiaPrimeiraController } from "./controllers/FindEucaristiaPrimeiraController";
import { FindCrismaController } from "./controllers/FindCrismaController";
import { ReadTurmaController } from "./controllers/ReadTurmaController";
import { ReadCatequeseAdultosController } from "./controllers/ReadCatequeseAdultosController";
import { ReadPessoaController } from "./controllers/ReadPessoaController";
import { ReadSacramentoController } from "./controllers/ReadSacramentoController";
import { ReadPadrinhoMadrinhaController } from "./controllers/ReadPadrinhoMadrinhaController";
import { ReadBatismoController } from "./controllers/ReadBatismoController";
import { ReadAdmissaoController } from "./controllers/ReadAdmissaoController";
import { ReadEucaristiaPrimeiraController } from "./controllers/ReadEucaristiaPrimeiraController";
import { ReadCrismaController } from "./controllers/ReadCrismaController";
import { UpdateTurmaController } from "./controllers/UpdateTurmaController";
import { UpdateCatequeseAdultosController } from "./controllers/UpdateCatequeseAdultosController";
import { UpdatePessoaController } from "./controllers/UpdatePessoaController";
import { UpdateSacramentoController } from "./controllers/UpdateSacramentoController";
import { UpdatePadrinhoMadrinhaController } from "./controllers/UpdatePadrinhoMadrinhaController";
import { UpdateBatismoController } from "./controllers/UpdateBatismoController";
import { UpdateAdmissaoController } from "./controllers/UpdateAdmissaoController";
import { UpdateEucaristiaPrimeiraController } from "./controllers/UpdateEucaristiaPrimeiraController";
import { UpdateCrismaController } from "./controllers/UpdateCrismaController";
import { DeleteTurmaController } from "./controllers/DeleteTurmaController";
import { DeleteCatequeseAdultosController } from "./controllers/DeleteCatequeseAdultosController";
import { DeletePessoaController } from "./controllers/DeletePessoaController";
import { DeleteSacramentoController } from "./controllers/DeleteSacramentoController";
import { DeletePadrinhoMadrinhaController } from "./controllers/DeletePadrinhoMadrinhaController";
import { DeleteBatismoController } from "./controllers/DeleteBatismoController";
import { DeleteAdmissaoController } from "./controllers/DeleteAdmissaoController";
import { DeleteEucaristiaPrimeiraController } from "./controllers/DeleteEucaristiaPrimeiraController";
import { DeleteCrismaController } from "./controllers/DeleteCrismaController";

const router = Router();

const createTurma = new CreateTurmaController();
const createCatequeseAdultos = new CreateCatequeseAdultosController();
const createPessoa = new CreatePessoaController();
const createSacramento = new CreateSacramentoController();
const createPadrinhoMadrinha = new CreatePadrinhoMadrinhaController();
const createBatismo = new CreateBatismoController();
const createAdmissao = new CreateAdmissaoController();
const createEucaristiaPrimeira = new CreateEucaristiaPrimeiraController();
const createCrisma = new CreateCrismaController();

const findTurma = new FindTurmaController();
const findCatequeseAdultos = new FindCatequeseAdultosController();
const findPessoa = new FindPessoaController();
const findSacramento = new FindSacramentoController();
const findPadrinhoMadrinha = new FindPadrinhoMadrinhaController();
const findBatismo = new FindBatismoController();
const findAdmissao = new FindAdmissaoController();
const findEucaristiaPrimeira = new FindEucaristiaPrimeiraController();
const findCrisma = new FindCrismaController();

const readTurma = new ReadTurmaController();
const readCatequeseAdultos = new ReadCatequeseAdultosController();
const readPessoa = new ReadPessoaController();
const readSacramento = new ReadSacramentoController();
const readPadrinhoMadrinha = new ReadPadrinhoMadrinhaController();
const readBatismo = new ReadBatismoController();
const readAdmissao = new ReadAdmissaoController();
const readEucaristiaPrimeira = new ReadEucaristiaPrimeiraController();
const readCrisma = new ReadCrismaController();

const updateTurma = new UpdateTurmaController();
const updateCatequeseAdultos = new UpdateCatequeseAdultosController();
const updatePessoa = new UpdatePessoaController();
const updateSacramento = new UpdateSacramentoController();
const updatePadrinhoMadrinha = new UpdatePadrinhoMadrinhaController();
const updateBatismo = new UpdateBatismoController();
const updateAdmissao = new UpdateAdmissaoController();
const updateEucaristiaPrimeira = new UpdateEucaristiaPrimeiraController();
const updateCrisma = new UpdateCrismaController();

const deleteTurma = new DeleteTurmaController();
const deleteCatequeseAdultos = new DeleteCatequeseAdultosController();
const deletePessoa = new DeletePessoaController();
const deleteSacramento = new DeleteSacramentoController();
const deletePadrinhoMadrinha = new DeletePadrinhoMadrinhaController();
const deleteBatismo = new DeleteBatismoController();
const deleteAdmissao = new DeleteAdmissaoController();
const deleteEucaristiaPrimeira = new DeleteEucaristiaPrimeiraController();
const deleteCrisma = new DeleteCrismaController();

router.post("/turma", createTurma.handle);
router.post("/catequeseadulto", createCatequeseAdultos.handle);
router.post("/pessoa", createPessoa.handle);
router.post("/sacramento", createSacramento.handle);
router.post("/padrinhomadrinha", createPadrinhoMadrinha.handle);
router.post("/batismo", createBatismo.handle);
router.post("/admissao", createAdmissao.handle);
router.post("/primeiraeucaristia", createEucaristiaPrimeira.handle);
router.post("/crisma", createCrisma.handle);

router.get("/turma/:idTurma", findTurma.handle);
router.get("/catequeseadulto/:idCatequeseAdultos", findCatequeseAdultos.handle);
router.get("/pessoa/:cpf", findPessoa.handle);
router.get("/sacramento/:idSacramento", findSacramento.handle);
router.get("/padrinhomadrinha/:cpfPessoa", findPadrinhoMadrinha.handle);
router.get("/batismo/:idSacramento", findBatismo.handle);
router.get("/admissao/:idSacramento", findAdmissao.handle);
router.get("/primeiraeucaristia/:idSacramento", findEucaristiaPrimeira.handle);
router.get("/crisma/:idSacramento", findCrisma.handle);

router.get("/turma", readTurma.handle);
router.get("/catequeseadulto", readCatequeseAdultos.handle);
router.get("/pessoa", readPessoa.handle);
router.get("/sacramento", readSacramento.handle);
router.get("/padrinhomadrinha", readPadrinhoMadrinha.handle);
router.get("/batismo", readBatismo.handle);
router.get("/admissao", readAdmissao.handle);
router.get("/primeiraeucaristia", readEucaristiaPrimeira.handle);
router.get("/crisma", readCrisma.handle);

router.patch("/turma/:idTurma", updateTurma.handle);
router.patch("/catequeseadulto/:idCatequeseAdultos", updateCatequeseAdultos.handle);
router.patch("/pessoa/:cpf", updatePessoa.handle);
router.patch("/sacramento/:idSacramento", updateSacramento.handle);
router.patch("/padrinhomadrinha/:cpfPessoa", updatePadrinhoMadrinha.handle);
router.patch("/batismo/:idSacramento", updateBatismo.handle);
router.patch("/admissao/:idSacramento", updateAdmissao.handle);
router.patch("/primeiraeucaristia/:idSacramento", updateEucaristiaPrimeira.handle);
router.patch("/crisma/:idSacramento", updateCrisma.handle);

router.delete("/turma/:idTurma", deleteTurma.handle);
router.delete("/catequeseadulto/:idCatequeseAdultos", deleteCatequeseAdultos.handle);
router.delete("/pessoa/:cpf", deletePessoa.handle);
router.delete("/sacramento/:idSacramento", deleteSacramento.handle);
router.delete("/padrinhomadrinha/:cpfPessoa", deletePadrinhoMadrinha.handle);
router.delete("/batismo/:idSacramento", deleteBatismo.handle);
router.delete("/admissao/:idSacramento", deleteAdmissao.handle);
router.delete("/primeiraeucaristia/:idSacramento", deleteEucaristiaPrimeira.handle);
router.delete("/crisma/:idSacramento", deleteCrisma.handle);

export { router };